name: CloneTest
on:
    push:
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - name: JDKInstall
          uses: Cla-Ver/pps-ci-lab/
          with:
            java-version: 21
        - name: Build
          run: ./gradlew check
